"""Preflight the ``senet`` environment (FR1.4) and resolve the stack (FR1.5).

Reports each required import as ``ok`` or ``FAIL`` with its resolved version, prints
the dict as JSON on **stdout** and commentary on stderr, and exits non-zero if any
required item failed. The exit code is load bearing: ``bash/embed_eve_subjects.sh``
gates the whole GPU run on it (FR11.9), the same pattern
``tools/osie_prep/check_features.py`` established for F1.

``versions.txt`` (FR1.5) is written by :func:`write_versions` from the *same*
resolution code, so the recorded stack cannot disagree with the checked one. That is
TechStack section 1.1's lesson made structural: F1's hand-written version table stayed
wrong until a tool read the file.

Every probe is wrapped, so this module runs to completion in a *broken* env -- which
is the only env where it is interesting.

CLI: ``py tools/eve_senet/check_env.py [--senet-dir DIR] [--versions PATH]``
"""

import argparse
import json
import os
import platform
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SENET_DIR = os.path.join(REPO_ROOT, "SE-Net")

# (label, probe, required). Probes are callables so a missing module raises inside
# the try rather than at module import -- see the docstring.
CHECKS = [
    ("python", lambda: platform.python_version(), True),
    ("torch", lambda: __import__("torch").__version__, True),
    ("cuda_available", lambda: str(__import__("torch").cuda.is_available()), True),
    ("torchvision", lambda: __import__("torchvision").__version__, True),
    ("numpy", lambda: __import__("numpy").__version__, True),
    ("scipy", lambda: __import__("scipy").__version__, True),
    ("timm", lambda: __import__("timm").__version__, True),
    # cv2 and sklearn are imported at MODULE SCOPE by SE-Net/common/utils.py, which
    # tools/eve_senet/dataset.py imports -- so a missing one is an ImportError before
    # any F3 code runs, not a runtime surprise. Neither is on F3's code path
    # (sklearn's only use there is `KFold` inside `fold_split`, which we never call),
    # but both must be *importable*. Added 2026-09-11 after `conda env create` left
    # them out: they live only in environment.yml's unusable pip section (see
    # TechStack section 1.2).
    ("cv2", lambda: __import__("cv2").__version__, True),
    ("sklearn", lambda: __import__("sklearn").__version__, True),
    ("detectron2", lambda: __import__("detectron2").__version__, True),
    ("msdeformattn", lambda: _probe_msdeformattn(), True),
]


def _probe_msdeformattn():
    """The import ``src/pixel_decoder/msdeformattn.py`` itself performs.

    Checking a different import would let a stale or missing ``make.sh`` build
    through -- the compiled extension is loaded by ``ops.modules``, not by the
    package ``__init__``.
    """
    if SENET_DIR not in sys.path:
        sys.path.insert(0, SENET_DIR)
    from src.pixel_decoder.ops.modules import MSDeformAttn  # noqa: F401
    return "import ok"


def resolve(senet_dir=SENET_DIR):
    """Run every probe. Returns ``(results, ok)`` -- never raises."""
    global SENET_DIR
    SENET_DIR = senet_dir
    results, ok = {}, True
    for label, probe, required in CHECKS:
        try:
            results[label] = {"status": "ok", "detail": str(probe()), "required": required}
        except Exception as exc:  # a broken env is the interesting case
            results[label] = {"status": "FAIL", "detail": repr(exc), "required": required}
            if required:
                ok = False
    # cuda_available imports fine but returning "False" is still a failure: F3's
    # forward passes are GPU work and a silently CPU-bound run must not look normal.
    cuda = results.get("cuda_available")
    if cuda and cuda["status"] == "ok" and cuda["detail"] != "True":
        cuda["status"] = "FAIL"
        ok = False
    return results, ok


def write_versions(path, results=None, senet_dir=SENET_DIR):
    """Write FR1.5's ``versions.txt`` from the same resolution code as the check."""
    if results is None:
        results, _ = resolve(senet_dir)
    lines = ["# resolved stack (FR1.5, D5) -- generated by tools/eve_senet/check_env.py",
             "executable\t{}".format(sys.executable)]
    for label, _, _ in CHECKS:
        entry = results[label]
        lines.append("{}\t{}\t{}".format(label, entry["status"], entry["detail"]))
    text = "\n".join(lines) + "\n"
    with open(path, "w") as fh:
        fh.write(text)
    return text


def main(argv=None):
    parser = argparse.ArgumentParser(description="Preflight the senet environment (FR1.4)")
    parser.add_argument("--senet-dir", default=SENET_DIR,
                        help="path to SE-Net/ (for the MSDeformAttn probe)")
    parser.add_argument("--versions", default=None,
                        help="also write FR1.5's versions.txt here")
    args = parser.parse_args(argv)

    results, ok = resolve(args.senet_dir)
    if args.versions:
        write_versions(args.versions, results, args.senet_dir)
    print(json.dumps(results, indent=2))
    for label, entry in results.items():
        sys.stderr.write("{:<16} {:<5} {}\n".format(label, entry["status"], entry["detail"]))
    sys.stderr.write("check_env: {}\n".format("OK" if ok else "FAILED"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
